config/routes.rb
Groominati::Application.routes.draw do

  match "/" => "main#index"

  resources :user_profiles
  devise_for :users
  resources :posts
  resources :comments

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  resources :reviews

  match 'tagged' => 'posts#tagged', :as => 'tagged' #for posts that have been tagged

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :user_profile, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :user_profile
  acts_as_follower
  acts_as_followable

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_profile_attributes


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_filter :authenticate_user!


  # GET /users
  # GET /users.json
  def index
    @users = User.all
    add_avatar_url



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # POST /users/1/follow
  # POST /users/1/follow.json
  def follow
    @user = User.find(params[:id])

    if current_user
      if current_user == @user
        flash[:error] = "You cannot follow yourself."
      else
        current_user.follow(@user)
        #RecommenderMailer.new_follower(@user).deliver if @user.notify_new_follower
        flash[:notice] = "You are now following #{@user.user_profile.user_name}."
      end
    else
      flash[:error] = "You must <a href='/users/sign_in'>login</a> to follow #{@user.user_profile.user_name}.".html_safe
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # POST /users/1/unfollow
  # POST /users/1/unfollow
  def unfollow
    @user = User.find(params[:id])

    if current_user
      current_user.stop_following(@user)
      flash[:notice] = "You are no longer following #{@user.user_profile.user_name}."
    else
      flash[:error] = "You must <a href='/users/sign_in'>login</a> to unfollow #{@user.user_profile.user_name}.".html_safe
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def add_avatar_url
    @users.each do |user|
      user[:avatar_url] = user.user_profile.avatar.url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>User Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
   <!-- <td><%#<%= user.name %></td>     -->
    <td><%= user.user_profile.user_name %></td>
    <td><%= image_tag user.user_profile.avatar.url(:thumb) %></td>
    <td><%= link_to 'Show Profile', user.user_profile %></td>
    <td><%= link_to 'Edit Profile', edit_user_profile_path(user.user_profile) %></td>
    <td><%= link_to 'Follow', follow_user_path(user), :method => :post %></td>
    <td><%= link_to 'Unfollow', unfollow_user_path(user), :method => :post %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
<% end %>

<%#<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
<%# <%= image_tag @user.avatar.url %>
<%#<%= image_tag @user.avatar.url(:medium) %>
<%# <%= image_tag @user.avatar.url(:thumb) %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>