config/routes.rb
Groominati::Application.routes.draw do

  match "/" => "main#index"

  resources :user_profiles
  devise_for :users
  resources :posts
  resources :comments

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  resources :reviews

  match 'tagged' => 'posts#tagged', :as => 'tagged' #for posts that have been tagged

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
    belongs_to :user
    attr_accessible :first_name, :last_name, :user_id, :avatar, :user_name
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_profiles }
    end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])

    #refactor this code out also we can probably just
    #get the avatar url and put it into a hash to pass to the view will be faster
    #also need to load up the posts better
    @followed_users_profile_list = Array.new
    @followed_users_post_list = Array.new
    followed_users = @user_profile.user.all_follows
    followed_users.each do |followed|
      @followed_users_profile_list << User.find(followed.followable_id).user_profile
      posts = User.find(followed.followable_id).posts
      posts.each do |post|
        @followed_users_post_list << post
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.json
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(params[:user_profile])

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render json: @user_profile, status: :created, location: @user_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.json
  def update
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      if @user_profile.update_attributes(params[:user_profile])
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end
end

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :user_name %><br />
      <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <tr>
    <th>User Name</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_profiles.each do |user_profile| %>
  <tr>
    <td><%= user_profile.user_name %></td>
    <td><%= user_profile.user.email %></td>
    <td><%= user_profile.first_name %></td>
    <td><%= user_profile.last_name %></td>
    <td><%= link_to 'Show', user_profile %></td>
    <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
    <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<p>
  <b>User Name:</b>
  <%= @user_profile.user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user_profile.user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user_profile.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user_profile.last_name %>
</p>

<p>
  <%= image_tag @user_profile.avatar.url(:medium) %>
</p>

<p>
  <b>Followed Users:</b></br>
  <% @followed_users_profile_list.each do |followed| %>
  <%= image_tag followed.avatar.url(:thumb) %>
  <%end%>
</p>


  <b>Followed Users Posts:</b></br>
  <% @followed_users_post_list.each do |post| %>
    <p>
      <b>Content:</b>
      <%= post.content %>
    </p>
    <p>
      <%= image_tag post.asset.url(:medium) %>
    </p>
  <%end%>



<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>